<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="classdiagrameditor" nsURI="http://classdiagrameditor/1.0" nsPrefix="classdiagrameditor">
  <eAnnotations source="gmf">
    <details key="foo" value="foo"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ElementoDiagrama" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nombreNoValido"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="nombreNoValido" value="Sequence{1 .. self.nombre.size()}->collect(i | self.nombre.substring(i, i))->excludes(' ')"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiagramEditor" eSuperTypes="#//ElementoDiagrama">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="clasesDistintoNombre"/>
    </eAnnotations>
    <eAnnotations source="gmf.diagram">
      <details key="foo" value="foo"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="clasesDistintoNombre" value="self.clases->isUnique(nombre)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clases" upperBound="-1"
        eType="#//Clase" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relaciones" upperBound="-1"
        eType="#//Relacion" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="agregaciones" upperBound="-1"
        eType="#//Agregacion" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composiciones" upperBound="-1"
        eType="#//Composicion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Clase" eSuperTypes="#//ElementoDiagrama">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="metodosDistintoNombre atributosDistintoNombre hijaDeSiMisma"/>
    </eAnnotations>
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="label.icon" value="false"/>
      <details key="tool.description" value="Clase"/>
      <details key="tool.name" value="Clase"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="metodosDistintoNombre" value="self.metodos->isUnique(nombre)"/>
      <details key="atributosDistintoNombre" value="self.atributos->isUnique(nombre)"/>
      <details key="hijaDeSiMisma" value="self->closure(padre)->excludes(self)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributos" upperBound="-1"
        eType="#//Atributo" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="layout" value="list"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metodos" upperBound="-1"
        eType="#//Metodo" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="layout" value="list"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="padre" upperBound="-1"
        eType="#//Clase" eOpposite="#//Clase/hija"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hija" upperBound="-1" eType="#//Clase"
        eOpposite="#//Clase/padre">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="closedarrow"/>
        <details key="style" value="solid"/>
        <details key="tool.description" value="Hija"/>
        <details key="tool.name" value="Hija"/>
        <details key="color" value="0,0,0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relaciona" upperBound="-1"
        eType="#//Relacion" eOpposite="#//Relacion/origen"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="es_relacionada" upperBound="-1"
        eType="#//Relacion" eOpposite="#//Relacion/destino"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="agrega" upperBound="-1"
        eType="#//Agregacion" eOpposite="#//Agregacion/origen_a"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="es_agregada" upperBound="-1"
        eType="#//Agregacion" eOpposite="#//Agregacion/destino_a"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compone" upperBound="-1"
        eType="#//Composicion" eOpposite="#//Composicion/origen_c"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="es_compuesta" upperBound="-1"
        eType="#//Composicion" eOpposite="#//Composicion/destino_c"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atributo" eSuperTypes="#//ElementoDiagrama">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre, tipo"/>
      <details key="label.icon" value="true"/>
      <details key="figure" value="rectangle"/>
      <details key="tool.description" value="Atributo"/>
      <details key="tool.name" value="Atributo"/>
      <details key="label.pattern" value="{0} : {1}"/>
      <details key="label.edit.pattern" value="{0}"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" eType="#//TiposBasicos"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TiposBasicos">
    <eLiterals name="binary"/>
    <eLiterals name="boolean" value="1"/>
    <eLiterals name="date" value="2"/>
    <eLiterals name="datetime" value="3"/>
    <eLiterals name="decimal" value="4"/>
    <eLiterals name="float" value="5"/>
    <eLiterals name="integer" value="6"/>
    <eLiterals name="string" value="7"/>
    <eLiterals name="text" value="8"/>
    <eLiterals name="time" value="9"/>
    <eLiterals name="timestamp" value="10"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Metodo" eSuperTypes="#//ElementoDiagrama">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="label.icon" value="true"/>
      <details key="figure" value="rectangle"/>
      <details key="tool.description" value="Método"/>
      <details key="tool.name" value="Método"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relacion" eSuperTypes="#//ElementoDiagrama">
    <eAnnotations source="gmf.link">
      <details key="target.decoration" value="arrow"/>
      <details key="target" value="destino"/>
      <details key="source.decoration" value="none"/>
      <details key="source" value="origen"/>
      <details key="style" value="solid"/>
      <details key="label" value="nombre"/>
      <details key="border.color" value="0,0,0"/>
      <details key="color" value="0,0,0"/>
      <details key="tool.description" value="Relación"/>
      <details key="tool.name" value="Relación"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origen" lowerBound="1"
        eType="#//Clase" eOpposite="#//Clase/relaciona"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destino" lowerBound="1"
        eType="#//Clase" eOpposite="#//Clase/es_relacionada"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Agregacion" eSuperTypes="#//ElementoDiagrama">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="agregadaPorSiMisma"/>
    </eAnnotations>
    <eAnnotations source="gmf.link">
      <details key="target.decoration" value="arrow"/>
      <details key="target" value="destino_a"/>
      <details key="source.decoration" value="rhomb"/>
      <details key="source" value="origen_a"/>
      <details key="style" value="solid"/>
      <details key="label" value="nombre"/>
      <details key="border.color" value="0,0,0"/>
      <details key="color" value="0,0,0"/>
      <details key="tool.description" value="Agregación"/>
      <details key="tool.name" value="Agregación"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="agregadaPorSiMisma" value="self.destino_a &lt;> self.origen_a"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origen_a" lowerBound="1"
        eType="#//Clase" eOpposite="#//Clase/agrega"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destino_a" lowerBound="1"
        eType="#//Clase" eOpposite="#//Clase/es_agregada"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Composicion" eSuperTypes="#//ElementoDiagrama">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="compuestaPorSiMisma"/>
    </eAnnotations>
    <eAnnotations source="gmf.link">
      <details key="target.decoration" value="arrow"/>
      <details key="target" value="destino_c"/>
      <details key="source.decoration" value="filledrhomb"/>
      <details key="source" value="origen_c"/>
      <details key="style" value="solid"/>
      <details key="label" value="nombre"/>
      <details key="border.color" value="0,0,0"/>
      <details key="color" value="0,0,0"/>
      <details key="tool.description" value="Composición"/>
      <details key="tool.name" value="Composición"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="compuestaPorSiMisma" value="self.destino_c &lt;> self.origen_c"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origen_c" lowerBound="1"
        eType="#//Clase" eOpposite="#//Clase/compone"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destino_c" lowerBound="1"
        eType="#//Clase" eOpposite="#//Clase/es_compuesta"/>
  </eClassifiers>
</ecore:EPackage>
